# Generated by Django 5.1.2 on 2024-12-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaints",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
