# Generated by Django 5.1.2 on 2024-10-19 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessories_name', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='Accessories')),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DogFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food_name', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='Food')),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOffered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='service_offered')),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookingAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('accessories_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.accessories')),
            ],
        ),
        migrations.CreateModel(
            name='BookingFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('Food_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.dogfood')),
            ],
        ),
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.serviceoffered')),
            ],
        ),
    ]
