# Generated by Django 5.1.2 on 2024-12-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accessories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_stock", models.PositiveIntegerField(default=1)),
                ("accessories_name", models.CharField(max_length=300)),
                ("image", models.ImageField(upload_to="Accessories")),
                ("price", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirm booking", "Confirm Booking"),
                            ("finished", "Finished"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
                ("appointment_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="BookingAccessories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price", models.PositiveIntegerField(blank=True, null=True)),
                ("total_price", models.PositiveIntegerField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.CharField(blank=True, max_length=200, null=True)),
                ("date", models.DateTimeField(auto_now=True)),
                (
                    "payement_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("COD", "Cash on Delivery"),
                            ("ONLINE", "Online Payment"),
                        ],
                        help_text="NB : If you choose online payment, after completing the payment you need to click  confirm button otherwise order will not be placed",
                        max_length=200,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookingFood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.PositiveIntegerField()),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("total_price", models.PositiveIntegerField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.CharField(blank=True, max_length=200, null=True)),
                ("date", models.DateTimeField(auto_now=True)),
                (
                    "payement_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("COD", "Cash on Delivery"),
                            ("ONLINE", "Online Payment"),
                        ],
                        help_text="NB : If you choose online payment, after completing the payment you need to click  'confirm booking' button to confirm order otherwise order will not be placed",
                        max_length=200,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookingService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.PositiveIntegerField()),
                ("date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Doctors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doctor_name",
                    models.CharField(blank=True, max_length=200, unique=True),
                ),
                ("specialized", models.CharField(blank=True, max_length=200)),
                ("availability", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="DogFood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_stock",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                ("Food_name", models.CharField(max_length=300)),
                ("image", models.ImageField(upload_to="Food")),
                ("price", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ServiceOffered",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=300)),
                ("price", models.PositiveIntegerField()),
                ("image", models.ImageField(upload_to="service_offered_image")),
            ],
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Token", models.CharField(max_length=200, unique=True)),
                ("token_available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TokenAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TokenService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                ("available", models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
    ]
