# Generated by Django 5.1.2 on 2024-10-19 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=200)),
                ('Token', models.CharField(max_length=200)),
                ('token_available', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('BOOKING CONFIRM', ' BOOKING CONFIRM'), ('COMPLETED', 'COMPLETED')], max_length=200)),
                ('username', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
