# Generated by Django 5.1.2 on 2024-10-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_doctors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='username',
        ),
        migrations.AlterField(
            model_name='doctors',
            name='Token',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doctor_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='status',
            field=models.CharField(choices=[('BOOKING CONFIRM', ' BOOKING CONFIRM'), ('COMPLETED', 'COMPLETED')], default='BOOKING CONFIRM', max_length=200),
        ),
    ]
