# Generated by Django 5.1.2 on 2024-12-24 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingaccessories",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("delivered", "Delivered"),
                    ("not delivered", "Not Delivered"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bookingfood",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("delivered", "Delivered"),
                    ("not delivered", "Not Delivered"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bookingaccessories",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="bookingfood",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="bookingservice",
            name="token",
            field=models.ForeignKey(
                blank=True,
                help_text="NB : Choose your Token based on Your service",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.tokenservice",
            ),
        ),
    ]
