# Generated by Django 5.1.2 on 2024-12-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_bookingaccessories_status_bookingfood_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingaccessories",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("delivered", "Delivered"),
                    ("not delivered", "Not Delivered"),
                ],
                default="not delivered",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bookingfood",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("delivered", "Delivered"),
                    ("not delivered", "Not Delivered"),
                ],
                default="not delivered",
                max_length=200,
                null=True,
            ),
        ),
    ]
