# Generated by Django 5.1.2 on 2024-11-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('confirm booking', 'Confirm Booking'), ('finished', 'Finished'), ('pending', 'Pending')], default='pending', max_length=200),
        ),
    ]
