# Generated by Django 5.1.2 on 2024-10-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_doctors_username_alter_doctors_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Token', models.CharField(max_length=200, unique=True)),
                ('token_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='Token',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='status',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='token_available',
        ),
        migrations.AddField(
            model_name='doctors',
            name='specialized',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
