# Generated by Django 5.1.2 on 2024-10-20 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_token_remove_doctors_token_remove_doctors_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CONFIRM BOOKING', 'CONFIRM BOOKING'), ('FINISHED', 'FINISHED')], default='CONFIRM BOOKING', max_length=200)),
                ('appointment_date', models.DateTimeField()),
                ('Token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.token')),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.doctors')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
