# Generated by Django 5.1.2 on 2024-12-06 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_bookingaccessories_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingaccessories",
            name="address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="bookingaccessories",
            name="email",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="bookingaccessories",
            name="payement_mode",
            field=models.CharField(
                blank=True,
                choices=[("COD", "Cash on Delivery"), ("ONLINE", "Online Payment")],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bookingaccessories",
            name="accessories_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.accessories",
            ),
        ),
        migrations.AlterField(
            model_name="bookingaccessories",
            name="price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
