# Generated by Django 5.1.2 on 2024-10-24 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_accessories_total_stock_bookingaccessories_quantity_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('Token', 'appointment_date')},
        ),
    ]
