# Generated by Django 5.1.2 on 2024-12-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_bookingaccessories_address_bookingaccessories_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingaccessories",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
