# Generated by Django 5.1.2 on 2024-10-26 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_appointment_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingaccessories',
            name='total_stock',
        ),
        migrations.RemoveField(
            model_name='bookingaccessories',
            name='accessories_name',
        ),
        migrations.RemoveField(
            model_name='bookingfood',
            name='Food_name',
        ),
        migrations.RemoveField(
            model_name='bookingservice',
            name='service_name',
        ),
        migrations.CreateModel(
            name='DogCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('accessories_name', models.CharField(max_length=200)),
                ('food_product_name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='Dog_Care_img')),
                ('total_stock', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_email', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Accessories',
        ),
        migrations.DeleteModel(
            name='BookingAccessories',
        ),
        migrations.DeleteModel(
            name='BookingFood',
        ),
        migrations.DeleteModel(
            name='DogFood',
        ),
        migrations.DeleteModel(
            name='BookingService',
        ),
        migrations.DeleteModel(
            name='ServiceOffered',
        ),
    ]
