# Generated by Django 5.1.2 on 2024-12-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_bookingfood_address_bookingfood_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingservice",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
