# Generated by Django 5.1.2 on 2024-12-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_bookingservice_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctors",
            name="availability",
            field=models.BooleanField(default=True),
        ),
    ]
