# Generated by Django 5.1.2 on 2024-12-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_doctors_availability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingaccessories",
            name="payement_mode",
            field=models.CharField(
                blank=True,
                choices=[("COD", "Cash on Delivery"), ("ONLINE", "Online Payment")],
                help_text="NB : If you choose online payment, after completing the payment you need to click  confirm button otherwise order will not be placed",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bookingfood",
            name="payement_mode",
            field=models.CharField(
                blank=True,
                choices=[("COD", "Cash on Delivery"), ("ONLINE", "Online Payment")],
                help_text="NB : If you choose online payment, after completing the payment you need to click  confirm button otherwise order will not be placed",
                max_length=200,
                null=True,
            ),
        ),
    ]
