# Generated by Django 5.1.2 on 2024-10-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_bookingservice_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffered',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
