# Generated by Django 5.1.2 on 2024-10-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_serviceoffered_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoffered',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_offered'),
        ),
        migrations.AlterField(
            model_name='serviceoffered',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceoffered',
            name='service_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
