# Generated by Django 5.1.2 on 2024-10-27 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_serviceoffered_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(blank=True, default=True, null=True)),
                ('token', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='serviceoffered',
            name='token',
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.tokenservice'),
        ),
    ]
