# Generated by Django 5.1.2 on 2024-10-27 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_tokenservice_remove_serviceoffered_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceoffered',
            name='available',
        ),
    ]
