# Generated by Django 5.1.2 on 2024-10-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_serviceoffered_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingfood',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dogfood',
            name='total_stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
