# Generated by Django 5.1.2 on 2024-10-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_bookingfood_quantity_dogfood_total_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingaccessories',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
