# Generated by Django 5.1.2 on 2024-11-07 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_bookingaccessories_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.token')),
            ],
            options={
                'unique_together': {('token', 'date')},
            },
        ),
    ]
